services:
  apisifytrade:
    public: true
    build: ./apisify_trade
    replicas: 1
    ports:
      - 80:8080
    resources:
      cpu: 1000m
      memory: 2Gi
    volumes:
      - data:/data

  apisifyview:
    public: true
    build: ./apisify_view
    replicas: 1
    ports:
      - 80:8501
    resources:
      cpu: 1000m
      memory: 3Gi
    volumes:
      - data:/data

  apisifyflow:
    public: true
    build: ./apisify_flow
    replicas: 1
    ports:
      - 80:5678
    environment:
      - DB_HOST=mysqldb://mysqldb:3306
    resources:
      cpu: 1000m
      memory: 2Gi
    volumes:
      - data:/data

  mysqldb:
    image: mysql:8.0.29
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    resources:
      cpu: 1000m
      memory: 1Gi
      storage: 1Gi

volumes:
  data:
    driver_opts:
          size: 4Gi
