services:
  apisifytrade:
    public: true
    build: ./apisify_trade
    replicas: 1
    ports:
      - 80:8080
    resources:
      cpu: 100m
      memory: 512Mi
    volumes:
      - data:/data

  apisifyview:
    public: true
    build: ./apisify_view
    replicas: 1
    ports:
      - 80:8501
    resources:
      cpu: 1000m
      memory: 3Gi
    volumes:
      - data:/data

volumes:
  data:
    driver_opts:
          size: 4Gi

endpoints:
  - path: /trade
    service: apisifytrade
    port: 8080
  - path: /view
    service: apisifyview
    port: 8501